### ISSUE TITLE
Feature Request: Option to show current DL / UL speed in window title and task bar

### ISSUE THREAD

**Issue by JustAndreww** [openscopeproject/TrguiNG#162]
I think it would be nice to show DL / UL speed here of the currently opened server:
![image](https://github.com/openscopeproject/TrguiNG/assets/4374611/eb70081f-d208-4ec2-be91-9f6de3f8094d)

And in taskbar:
![image](https://github.com/openscopeproject/TrguiNG/assets/4374611/90f5636c-5479-43cb-84a4-4c827a934d5e)

Maybe also when you hover your mouse over the tray icon in a non-existent yet popup balloon :)

**Comment by qu1ck** [comment]
I added speeds to window title. In taskbar the string shown is same as window title, there is no separate control over it. And it's more important to show the application name, which is why it's first.

For tray icon I considered it but that would require constantly polling 2 more fields even in background mode. Not worth the increase in network usage.

**Comment by qu1ck** [comment]
Implemented in [v1.2.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v1.2.0)
