### ISSUE TITLE
Feature request: better label management

### ISSUE THREAD

**Issue by slundi** [openscopeproject/TrguiNG#175]
Hi

Is it possible to have those UI improvements:
- specify label(s) while adding torrent
- when setting label on a torrent, the select is hiding the **Save** and **Cancel** buttons
- with a right click, in the menu: can we have the existing label list to apply them on torrents
- always keep some labels (movie, tv, anime, game, ...) because when no torrent have the label it disappears

Regards

**Comment by qu1ck** [comment]
> specify label(s) while adding torrent

It is supported. Update your transmission server to v4

> when setting label on a torrent, the select is hiding the Save and Cancel buttons

Yes. Do you have a better suggestion? The multiselect ui element with ability to add free form text is the only one that fits the requirements here. Only thing I can think of that can replace it is a much more complex multi checkbox list + a separate add button which is worse in my opinion than just a click to hide the dropdown.

> with a right click, in the menu: can we have the existing label list to apply them on torrents

No, such UI would give a false impression that labels can be added/removed without affecting existing labels of torrents but that is not how transmission's api works. 

> always keep some labels (movie, tv, anime, game, ...) because when no torrent have the label it disappears

This can be added

**Comment by jpovixwm** [comment]
> No, such UI would give a false impression that labels can be added/removed without affecting existing labels of torrents but that is not how transmission's api works.

I think this could work if it was restricted to single row selection. Make it a submenu with all the currently-applied labels with checkmarks to the left of each item, together with known and not-yet-applied labels without checkmarks. This would make it possible to quickly apply or remove a label from a single torrent.
However, having the context menu stay open after toggling a label, to enable the quick toggling of more than one label, could be a bit tricky because then it would probably need to be debounced somehow if the user toggles a couple of labels in quick succession, which opens another can of worms😕

**Comment by qu1ck** [comment]
> So I'll have to install it manually.

Docker image is best if you want fast updates without the hassle of compiling yourself.

> Moving the buttons to the top? Increase height of the dialog (to display maybe 5 lines) with empty space

I will play with this idea and see how it looks in practice

> With icons to be fancy?

No icons, it will be user configurable and empty by default because everyone uses different labels and even in different languages.

**Comment by jfeilbach** [comment]
@slundi See https://forums.linuxmint.com/viewtopic.php?p=2369958#p2369958

**Comment by qu1ck** [comment]
Implemented in [v1.3.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v1.3.0)
