### ISSUE TITLE
Feature request: some suggestions

### ISSUE THREAD

**Issue by Beau-Yang** [openscopeproject/TrguiNG#181]
Hi, 

Is it possible to have those improvements:

1. Support adding mutiple torrents by magnet link or URL at a time;

The following is the iterface of **VueTorrent** (one alternative WebUI of qBittorrent) to add torrents at a time via links:
- Different links are written on different lines
![image](https://github.com/openscopeproject/TrguiNG/assets/49222826/a6dcb8fa-8e2d-49fc-8b29-5bea5389d4af)

2. Counts and displays the file sizes of different trackers;

It would be very convenient for users to manage if the file size of the corresponding tracker is displayed after each tracker in the left pane.

For example,
![1e2447f53eb00844d18102299875cf9](https://github.com/openscopeproject/TrguiNG/assets/49222826/87d8643f-9573-4620-8790-fda1734e21ca)

Another TR WebUI **transmission-web-control** has a similar feature.

3. Set seperate speed limits for different trackers.

Anyway, thanks for your amazing work! TrguiNG is the best TR WEBUI I‘ve ever used! Smooth and Elegant!

For reference:
VueTorrent: https://github.com/VueTorrent/VueTorrent
transmission-web-control: https://github.com/ronggang/transmission-web-control

**Comment by qu1ck** [comment]
1) and 3) are not supported by transmission API, you should ask for these features to be implemented on the server before I can add support for them in the UI. Transmission added support for bandwidth groups recently, although it is half baked. Potentially you could use that if you set up separate group for each tracker and then add your torrents to corresponding groups.

2) is possible but I don't think this adds value because you can already easily check the size by tracker if you click on that tracker to filter torrent table and then look at "Total" in the status bar 
![image](https://github.com/openscopeproject/TrguiNG/assets/3622532/7b4d7856-fac9-4886-b9f3-ad9779325f5b)

**Comment by Beau-Yang** [comment]
Thanks for your response. But I want to provide more information about the suggestion (1). The transmission-web-control which I mentioned below somehow realizes adding multiple torrents by URLs at a time. The following is the screenshot of it.

![E6DDD187D91F5477A8DF48066BD59D06](https://github.com/openscopeproject/TrguiNG/assets/49222826/1357aadd-d76d-4899-b6f9-47c03fa06dc9)

I need to say sorry because it's a Chinese version and can't be changed to English. But the yellow area I marked says "Copy torrent links to list, separate multiple seeds with carriage returns". I tried it and managed to add multiple seeds at once. Could you please check it?

The GitHub link of it is https://github.com/ronggang/transmission-web-control.

Thanks again for your help.

**Comment by qu1ck** [comment]
As I thought, they implement batch adding torrent links by issuing separate API requests in a loop. It is possible but quite a bit of work to do correctly in a multi-client app like TrguiNG. And it's something that is much more suitable to do with transmission-remote cli and some scripting because it's very niche feature.

However if transmission adds multi-add API I will implement support for it.
