### ISSUE TITLE
Make all Magnet icons red so they are more recognizable/consistent as magnet icons?

### ISSUE THREAD

**Issue by Pentaphon** [openscopeproject/TrguiNG#186]
![mag](https://github.com/openscopeproject/TrguiNG/assets/49374058/b9cbe7ac-dd37-4629-8273-75f3e12c4fe4)

Here's how they look in both the toolbar and the torrent list. Can you make them both red instead of blue/green? It would make the icon more consistent and recognizable as a magnet icon. Perhaps a different shade of red than the error icon and remove torrent icon if that is an issue?

**Comment by qu1ck** [comment]
No, red signifies error state and magnetizing is essentially a substate of downloading so they will have same color in the torrent list and filter. In the toolbar both add torrent and add magnet could be blue but I like that it's different from neighboring start/stop buttons. I don't think it's a big deal that those 2 magnet icons are different color because they have different semantics.
