### ISSUE TITLE
improve torrent error logic

### ISSUE THREAD

**Issue by trim21** [openscopeproject/TrguiNG#196]
Let's say, I have two kind of torrents. BT(public tracker) torrents and PT(private tracker, with `isPrivate=true` in api) torrents,.

I hope to imporve torrent error logic, so is a torrent is private, **any** tracker in pt torrent return a message is consider error. And if it's not private, **all** trcker in bt torrent return a message is consider error.

**Comment by trim21** [comment]
for example, this is a private tracker:
![image](https://github.com/openscopeproject/TrguiNG/assets/13553903/7802bc87-b7a6-40fb-b77d-67fd697f55ff)
and I hope this can be consider error.

**Comment by trim21** [comment]
And I can send a pr to impl this

**Comment by qu1ck** [comment]
I'm not sure that would be an improvement. I'm assuming for private tracker torrents vast majority have only one tracker and for rare cases where they have multiple they are effectively the same and act as backups. In this case "one failure = error" logic does not make sense.

And there is also the downside of having to add another field isPrivate to the list of always pulled fields which increases network traffic.

**Comment by trim21** [comment]
You are partially right, there are 2 kinds of errors here, retryable error and non-retryable error. for example, retryable temporary network error and non-retryable error like "torrent removed".

It's true they should effectively the same, but in this case, not all tracker return same response. because some transmission won't announce to some trackers.

in this case, transmission will consider 2 trackers "backup", and won't annoucne to them

![image](https://github.com/openscopeproject/TrguiNG/assets/13553903/f4ae0547-5cc2-4156-b48e-e6a62369b95d)

in api, you can find 3rd tracker with `isBackup: false` and 1st and 2rd tracker `isBackup: true`


`isPrivate` is already fetch. but even it doesn't, 10000 torrent with a extra field just add 10kb to network traffic.

**Comment by trim21** [comment]
and I'm gussing, if there are no network errors, transmission won't announce to next tracker...

https://github.com/transmission/transmission/issues/890#issuecomment-1048072932

**Comment by qu1ck** [comment]
That same comment you linked says that in case of failure next successful tracker in the same tier will be tried and bumped to the top if it succeeds. So it's enough to check the first one, like current implementation. Unless the api does not reorder the tracker list in the response?

> 10000 torrent with one extra field would just add 10kb to network traffic...

Its json, it's a lot more than 1 byte per entry in plain text and even gzipped it would be at least 3-5 bytes.

**Comment by trim21** [comment]
> That same comment you linked says that in case of failure next successful tracker in the same tier will be tried and bumped to the top if it succeeds. So it's enough to check the first one, like current implementation. Unless the api does not reorder the tracker list in the response?

api will always order trackerStats in the same order with tracker url in torrent's `announce-list`, the "bump" is internal only.

> Its json, it's a lot more than 1 byte per entry in plain text and even gzipped it would be at least 3-5 bytes.

160 torrent is already 28kb, so even 10000 torrent would be 1750kb. so even 50kb, would be and roughly 2% increase.

**Comment by qu1ck** [comment]
> api will always order trackerStats in the same order with tracker url in torrent's announce-list, the "bump" is internal only.

If that's the case then I would welcome a change that checks for first non-backup tracker instead of simply first tracker.

> 160 torrent is already 28kb, so even 10000 torrent would be 1750kb. so even 50kb, would be and roughly 2% increase, it's even less than 1/1000 after gzipped.

That part I'm planning to improve at some point on transmission side because the api currently does not support querying specific subfields of heavy composite fields like trackerStats. That field alone takes up majority of a typical response. Once that is fixed every single field will be not 1-2% extra but more like 5-10% extra.

Besides there are a lot of people that:
1. Use transmission remotely on internet seedboxes and may be on metered connections.
2. Use transmission on raspberry PIs or small appliance type NAS devices that share similarity with toasters not just in external dimensions but also in CPU power. I had one such device that would literally stall on downloads/seeding because all of it's brains were busy generating json for the API response instead of handling p2p comms. That was even more of an issue on earlier transmission versions that were not properly multithreaded.

**Comment by qu1ck** [comment]
Fixed in [v1.4.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v1.4.0)
