### ISSUE TITLE
Feature Request: Add torrents in background

### ISSUE THREAD

**Issue by Cris--** [openscopeproject/TrguiNG#209]
Hi,

if i open a .torrent in Windows and running TrguiNG in the background (tray only), TrguiNG window is opening.
Add an option please: Add torrents in background only.

**Comment by qu1ck** [comment]
Sorry, this is unlikely to ever be implemented because of the architecture of the app. Adding torrents is implemented in the frontend which requires the window to be open to work.

Best I can offer is an option to not pop the window into focus if "Skip add dialog" is enabled, this way the torrent will be added silently if the window is in the background.

**Comment by qu1ck** [comment]
On further investigation not popping the window into focus may not reliably wake up the front end javascript engine if the window was hidden for a while on some systems. So this is not feasible as far as I can tell.
