### ISSUE TITLE
Inflated number of seeds/peers

### ISSUE THREAD

**Issue by melyux** [openscopeproject/TrguiNG#22]
I know there's [no optimal way](https://stackoverflow.com/questions/10802134/calculate-total-number-of-actual-seeders) to know the exact number of total seeds and peers for a download, but the current strategy of adding all the seeds and peer numbers from all the trackers seems a overly optimistic :)

Transmission Remote GUI seems to use the maximum number for each from the trackers instead, which seems like a good compromise since usually the overlap between their common seeds/peers is close to 100%. Thoughts?

**Comment by melyux** [comment]
P.S. Might also be good to display blank instead of -1 for trackers that have no valid seeds/peers numbers:

<img width="380" alt="image" src="https://github.com/openscopeproject/TrguiNG/assets/10296053/8e3d9130-9494-4c84-8b1a-d72adc78e31f">

**Comment by qu1ck** [comment]
The overlap depends significantly on if the torrent and trackers are public or not. 
For private torrents that are uploaded to multiple trackers overlap may be close to 0.

I think these numbers don't mean much beyond a very rough gauge of how healthy the swarm is and there is an argument that even if peers overlap between trackers, having those peers on multiple trackers means healthier combined swarm and should reflect on the numbers.

Agree on the blank instead of -1, will be fixed soon.

**Comment by Pentaphon** [comment]
> I think these numbers don't mean much beyond a very rough gauge of how healthy the swarm is

I agree with @melyux . People on public trackers tend to just throw all the announce URLs on their torrents so he current strategy of adding all the seeds and peer numbers from all the trackers is almost always going to result in vastly overinflated peer numbers. Seriously, there's guides all over the web telling people to do this and 4.x now has a default public trackers field so adding as many announce URLs to a torrent as you want is easier now than it ever has been. I think a lot of people are going to complain about this as TrguiNG gets more popular so it would be best to just reflect reality or at least what is most likely, and just do what all the other clients do to report peer counts. 

>there is an argument that even if peers overlap between trackers, having those peers on multiple trackers means healthier combined swarm and should reflect on the numbers.

If the number of peers is usually much bigger than what it really is, then the client is just misinforming people and I don't think users will take that well. This will be one of many issues raised about this display count There is no way to have peer overlap reflect in the numbers because we can't calculate exactly how healthy the swarm is from having more trackers connected to the same amount of peers, so TrguiNG shouldn't make any assumptions. I think the inflated number of peers should be removed before this becomes a bigger issue. Frontends should always reflect what the backend shows. If they don't, people will just stop using TrguiNG out of frustration.

**Comment by qu1ck** [comment]
> so TrguiNG shouldn't make any assumptions

so... you are asking that TrguiNG show a max, which is just another assumption?

> Frontends should always reflect what the backend shows

Yes. And when backend gives you 3 numbers and you want to show it in an aggregate way in a single column the way you aggregate is up to interpretation. It's not like TrguiNG just made up the numbers that are in disagreement with backend.

> there's guides all over the web telling people to do this

Any links?

My experience may well be skewed with private trackers and public ones that don't report peer counts. If there is some agreed common approach here discussed with arguments, I'd like to read up on it.

**Comment by Pentaphon** [comment]
> so... you are asking that TrguiNG show a max, which is just another assumption?

No, I am asking that if there's 10 announce URLs with 1 peer in each one, the number of peers should be reported as 1

>Yes. And when backend gives you 3 numbers and you want to show it in an aggregate way in a single column the way you aggregate is up to interpretation. It's not like TrguiNG just made up the numbers that are in disagreement with backend.

The key part of this is "and you want to show it in an aggregate way". Nobody wants 1 peer with 3 announce URLs to be shown as 3. It should be 1, because there's only 1 peer.

>Any links?

https://lmgtfy.app/?q=add+trackers+to+torrents

Literally countless guides telling people to "increase speed" by adding trackers to their torrents. This along with the new 4.x feature to add default trackers, there's many people online who add trackers to their torrents to hopefully get more peers, on top of already using the DHT.

**Comment by qu1ck** [comment]
> No, I am asking that if there's 10 announce URLs with 1 peer in each one, the number of peers should be reported as 1

Right, so you are asking to aggregate the numbers by max, like I said. Because I'm assuming when you have 3 trackers and 2 of them show 1 and another shows 4, you want the column to show 4, which is the max.

> The key part of this is "and you want to show it in an aggregate way". Nobody wants 1 peer with 3 announce URLs to be shown as 3 peers. It should be 1, because there's only 1 peer.

I can just as well say "nobody cares about that number because it's highly inaccurate anyway" and we'd both be making wrong generalization about what everyone wants or doesn't want. But I would be right on inaccuracy part because this number:

* does not include any peers that trackers not reporting peer counts have
* does not include any dht peers
* does not include any pex peers
* for multiple trackers gives no way of determining actual unique peers

If you think that 3 trackers reporting 1 peer means there is actually 1 peer you are misinterpreting the information. It only means that each of those trackers know of 1 peer that reported to them at some point. It may be same one, different one, there may be others, there may not be even that one because he disconnected hours ago.

> Literally countless guides telling people to "increase speed" by adding trackers to their torrents.

Ah, I thought you meant guides to correct way to aggregate reported peer numbers. Advice to add trackers makes sense but is not relevant here.

What matters for your speeds is how many peers you actually connect to and the number of reported total peers makes no difference.

> new 4.x feature to add default trackers

No idea what you mean here, is that some button in GUI? Which GUI? Is it during torrent creation or adding to transmission? What are default trackers?

I don't even feel strongly about this but I'm not hearing any convincing argument to why a rough guess of sum(tracker peers) is any worse than rough guess of max(tracker peers). I will likely make this an option later.

I looked at hundreds of torrents I'm seeding right now and the worst offender I could find was a torrent that is showing 1800 peers with a dozen trackers having 100-200 peers each. Does it have literally 1800 peers? Most likely not. Does it have more than 200? Most likely yes. Is showing 1800 better than showing 200 as a gauge of how healthy the swarm is? I think yes because this torrent is likely healthier than a torrent with single private tracker with just 200 peers. And it seems to me that's the only use for this number because of how inherently inaccurate it is anyway.

**Comment by Pentaphon** [comment]
I just think that @melyux is correct and the number of seeds/peers is inflated and that:

>Transmission Remote GUI seems to use the maximum number for each from the trackers instead, which seems like a good compromise since usually the overlap between their common seeds/peers is close to 100%. Thoughts?

is preferable to what happens now. There's no need to go beyond what other frontends do since all users want all frontends to report the same stats.

**Comment by qu1ck** [comment]
I spot checked 5 other clients and they either don't show total at all (tremotesf at least on screenshots, official ones), have used sum and only recently switched to max (transmission-remote-gtk) or are in Chinese and I can't be bothered to dig into the code. 

But a recent refactoring made the change super easy so what the heck, I'll keep my early adopters happy :)

**Comment by melyux** [comment]
The convo took some tense turns up there but gotta admit I'm happy with where it ended up landing ;)

**Comment by Pentaphon** [comment]
> But a recent refactoring made the change super easy so what the heck, I'll keep my early adopters happy :)

Thank you. Really, this was the best choice in the long run.
