### ISSUE TITLE
Feature request: open file selection window after fetching index file for magnet link

### ISSUE THREAD

**Issue by Antiwh0re** [openscopeproject/TrguiNG#235]
Hello!
I've come across a missing core feature.
When I add a magnet link to the app and it fetches the .torrent file for it, it doesn't ask me which files to download like with usual torrents, but starts downloading all files from the torrent at once. This is stupid, because obviously I don't need all files from all the torrents I'm downloading and the app must provide me with a choice.
I haven't found the setting to activate this behavior, so it's missing. As far as I remember, this feature was present in all other clients I've used. And it's begging to be implemented here as well. Will you do it?

**Comment by qu1ck** [comment]
I have not seen this feature in any of the clients I've used. And I have a hard time imagining how it can work reliably.

The app does not download metadata for magnet links, the transmission server does. It may do it in 5 seconds, 5 hours or never, app has no way to know when it will happen. If you happen to not have the app running when metadata completion finishes, then what?

If you think it's important then you can ask transmission devs for a feature to have magnet links download metadata even if they are added as stopped. Then you will have an option to come back later and choose files you want before starting the torrent.

**Comment by Antiwh0re** [comment]
I don't need to imagine it cause I've seen it working in clients just fine. The latest client was KTorrent and it had a separate panel for added magnet links, and when one of the links caught the index file, the app immediately opened the file selection window for it just as usual torrents.
Watching the server is not a problem at all - your app needs to watch the magnets only when it's open and leave their treatment to transmission when it's not. When it's open and the magnet catches the index, it must send a command to transmission to stop the download and open the file selection window for this torrent.
I won't go and ask transmission devs of anything because I've already asked you to implement it and it's no problem to do so as I've described above. Besides that what you offered is not a solution - as selection window won't be opened, I won't see that the index was fetched for this magnet at once.
After all these considerations your answer implies you just don't want to implement it, do you?

**Comment by qu1ck** [comment]
KTorrent is not a transmission daemon cilent, it's a torrent client in itself. It can do things that my app can not do because my app is not a torrent client, it is limited to what transmission api allows it to do.

> Watching the server is not a problem at all - your app needs to watch the magnets only when it's open and leave their treatment to transmission when it's not. When it's open and the magnet catches the index, it must send a command to transmission to stop the download and open the file selection window for this torrent.

This is not reliable in any way. You may lose connection to your server. It may not be fast enough to send a stop command and transmission will allocate file space for your unwanted files anyway. Your server may get rebooted and change torrent ids and magnetization status and the app will not be able to detect that, lots of things can go wrong.

> Besides that what you offered is not a solution - as selection window won't be opened, I won't see that the index was fetched for this magnet at once.

That's the best solution you will get in the split architecture we have with the separate server (torrent client) and gui (talking to server via polling style api).

> After all these considerations your answer implies you just don't want to implement it, do you?

Yes, I don't want to implement an unreliable half-assed feature and I don't see a way to make it reliable with limitations of existing transmission api.

**Comment by Antiwh0re** [comment]
Oh yeah, limitations of API... You imply that API allows you to catch index fetching event for magnets to change their status from Magnetizing to Running, but it doesn't allow you to stop the torrent and open a window after this same event. This sounds like a load of bullshit, and so can be everything else.
You just don't want to do the job that takes significant effort. What is more disgusting, you're trying to cover your laziness with evasions using your knowledge, which I don't have. You must be ashamed.

**Comment by qu1ck** [comment]
Honestly, at first I didn't even want to indulge this entitlement filled diatribe with a response.

But for the sake of people who may have similar idea in the future and stumble upon this issue after a search. Here is a more detailed explanation regarding technical part.

> You imply that API allows you to catch index fetching event for magnets to change their status from Magnetizing to Running, but it doesn't allow you to stop the torrent and open a window after this same event. This sounds like a load of bullshit, and so can be everything else.

I imply no such thing. There are no events, transmission api is not event driven, it is polling based. Every X seconds my app asks transmission "give me a list of torrents you have and their details, including status, etc.". Then it draws the list according to transmission response. That's it. The only "processing" it does on the list is try to detect which torrents were downloading last time and are finished this time, then issue a notification about completed download. Even this is happening on a best effort basis.

Here is what can happen after a magnet link was added:
1. At time `t` TrguiNG polls the server, it returns torrent with status "downloading metadata"
2. At time `t+1` the server completes downloading metadata and immediately starts downloading the torrent
3. At time `t+2` the server received some chunks and preallocates space on the hard disk for files
4. At time `t+3` TrguiNG polls the server again, it is already in downloading status and has 0.1% or 1% or whatever downloaded.

At no point in between 1 and 4 can the app do anything at all. And after 4) it is already late to select files because space is preallocated anyway, transmission does not clear it even if you mark some files as skipped later.

You may argue that the app just has to poll fast enough to catch the server between 2) and 3) and stop the torrent and my response to that is that there is no way to do it reliably and it would require unreasonably high polling rate anyway.

Now, with the technical part out of the way...

> You just don't want to do the job that takes significant effort. What is more disgusting, you're trying to cover your laziness with evasions using your knowledge, which I don't have. You must be ashamed.

I'm sorry, did you mistake me for your employee? Or did you buy something from me with a service contract? Whatever makes you think I just owe you my time?

With all due respect, which is none at this point, here is some advice given as free as the software I wrote: 

Get some manners.

It may do you good next time you ask a complete stranger for something. Even if your feature request was viable, with that kind of attitude you will likely get ignored at best and laughed out the door at worst.
