### ISSUE TITLE
Copy magnet link of torrent using right click and Command + C

### ISSUE THREAD

**Issue by melyux** [openscopeproject/TrguiNG#24]
It would be cool to be able to copy a torrent's magnet link by just doing Command + C when it's selected. And adding it to the right click menu for a torrent too

**Comment by qu1ck** [comment]
Clipboard integration will not be implemented, see https://github.com/openscopeproject/TrguiNG/issues/18#issuecomment-1610276070

> And adding it to the right click menu for a torrent too

You mean in Finder? I'm assuming you are still on macos. That should work now, maybe you need to remove the app and then copy it to applications again since the app metadata changed. At least I get TrguiNG option in Open with submenu in finder on right click.

**Comment by qu1ck** [comment]
Sorry looks like I misread the request, I think you are asking to have option to copy magnet link of already existing torrent from the torrent context menu in TrguiNG. Yeah, that can be added.
