### ISSUE TITLE
minor UX quibbles

### ISSUE THREAD

**Issue by mshapcotte** [openscopeproject/TrguiNG#35]
All the below relate to Windows version 0.6.0:

1. control-r reloads the entire UI instead of reannouncing selection
2. up/down arrows scroll instead of changing the selection
3. control-i clears the current filter selection

Perhaps 1 & 2 both stem from the Windows app being built on web tools...

**Comment by qu1ck** [comment]
1. I specifically didn't assign the shortcut because a) it's a rarely needed function and b) it would clash with a web version of TrguiNG because there it needs to reload the page and I want to minimize the differences when possible.
2. This one is actually because of the web tools. Making it work is too much effort because of differences between keyboard event propagation models in web and traditional UIs. Maybe I'll revisit this at some point when things slow down.
3. Fixed.

**Comment by mshapcotte** [comment]
Built v0.6.0-5-ge8daf0e-dirty and indeed #3 is fixed -- thank you!

**Comment by qu1ck** [comment]
Fixed in [v0.7.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v0.7.0)

Created #46 to track keyboard arrows, low priority for now.
