### ISSUE TITLE
Make statistics readable without scrolling in 3-pane layout on small screens

### ISSUE THREAD

**Issue by Pentaphon** [openscopeproject/TrguiNG#47]
When the 3 pane layout is activated, the statistics panel, at least on my layout, needs to be scrolled to be completely read.

This is a small piece of information and it should be fully readable without scrolling, even on a small panel, but you need to scroll just to read the whole thing. Any chance you can optimize the layout of the statistic? Maybe lay it out horizontally rather than vertically? Make 2 columns side by side, 1 for session, 1 for cumulative? Perhaps make it 2 column when the pane is made smaller but keep it the same when it gets bigger?

Or...maybe make the statistics window pop up a tiny window in the middle of the screen like the official client does instead of using the 3rd pane at all?

![stat](https://github.com/openscopeproject/TrguiNG/assets/49374058/8c1f9e9b-f9af-40ca-bae8-4e2adacf1c2d)

**Comment by qu1ck** [comment]
Problem with this one is that if I make it into 2 columns then it looks redundant to repeat same field names and it makes sense to combine it into one table. But then it's too wide for the vertical layout.

I think it's better as is because it works same way in both layouts. Also it's already shorter than the much more used General tab which people would normally adjust the height of details panel for. If you make it big enough to not have scrolls in general tab it will not have scrolling here either.

> Or...maybe make the statistics window pop up a tiny window in the middle of the screen like the official client does instead of using the 3rd pane at all?

That would require closing the pop up to use other controls which I'd like to avoid.

**Comment by Pentaphon** [comment]
Ok fair enough. It was just an idea but if you're not open to it, I'll just close this.
