### ISSUE TITLE
day/night mode option to match system

### ISSUE THREAD

**Issue by melyux** [openscopeproject/TrguiNG#49]
Could a 3rd/default option be to match TrguiNG's theme to the system's night/day mode settings?

**Comment by qu1ck** [comment]
Current default is already supposed to match the system theme. The api just doesn't work reliably enough on all platforms. Not much I can do here without investing significant effort into researching native API calls and bypassing tauri completely.

Or do you mean 3rd option that would match a dynamic switching theme? I don't think there is an API for that at all because as far as I know only macos has that feature.

**Comment by melyux** [comment]
I just meant matching the system's current dark mode boolean. It's supposed to do that? But doesn't work yet on Mac?

**Comment by qu1ck** [comment]
Yes, it's supposed to do that and does, at least on linux. But it only does if you haven't manually switched the theme in the app, if you do then that value is stored in config.

**Comment by melyux** [comment]
In that case the 3rd option for the theme toggle would be to clear the config to match the system, if supported

**Comment by qu1ck** [comment]
Then the toggle button doesn't work and you need a 3 way switch with labels, which can't go in the toolbar.

Not worth it.

**Comment by melyux** [comment]
No way for a 3 way toggle? Kind of weird to have the current one irreversibly mess up auto theming when you touch it though

**Comment by qu1ck** [comment]
3 way toggles are possible as well as 5 way like the font toggle. But this one will be confusing without labels explaining what the states are and there is no space for labels on the toolbar.

>  mess up auto theming

Think of it as a best guess default setting instead of auto theming because there is no reliable auto theming.
