### ISSUE TITLE
Show files in prompt when adding a torrent to de-select/select the files you want

### ISSUE THREAD

**Issue by Pentaphon** [openscopeproject/TrguiNG#54]
Basically have the same kind of prompt with file selector as TransGUI

![new](https://github.com/openscopeproject/TrguiNG/assets/49374058/41f04a43-b0d3-4595-ae6a-68a0b4efeea4)

**Comment by qu1ck** [comment]
It's already there

![image](https://github.com/openscopeproject/TrguiNG/assets/3622532/90daae8b-71b4-44c6-a43f-d6db44ce1c84)

It does not show up in a few cases where it does not make sense like if you are batch adding torrents or torrent has a single file. Also it is not supported in web version because it does not parse the torrent itself.

**Comment by Pentaphon** [comment]
> Also it is not supported in web version because it does not parse the torrent itself.

Ah, this is my issue then. I should have known since the official web client does not do this.
