### ISSUE TITLE
Can't deselect with Ctrl

### ISSUE THREAD

**Issue by enchained** [openscopeproject/TrguiNG#6]
I'm used to selecting multiple torrents in transgui, so the first thing I noticed here is that if I'm selecting torrents one by one with the Ctrl key, I can't deselect one if I selected it by mistake. 

Slight GUI issues I also noticed: 
* When torrent details load for the first time at the bottom, it "blinks" and tabs "jump" vs previous selected torrent. Especially noticeable when doing the multi-selection. Transgui felt more static in that regard. Maybe some placeholders could make the loading look more smooth.
* I'm used to seeing the free space at a glance, but here it feels harder to focus on specific parts of the status bar. Maybe some spacing and separators could improve the readability a bit?

Other than that, TrguiNG looks and feels simply amazing. Will keep testing. Please, keep up the good work!

I was also wondering, did you ever consider supporting other clients, like qBittorrent? I feel like there's close to none native apps for other clients, and Electorrent doesn't have path mapping or location selection, sadly.

**Comment by qu1ck** [comment]
Thanks, this is great feedback.

>  I can't deselect one if I selected it by mistake

Fixed

> When torrent details load for the first time at the bottom, it "blinks" and tabs "jump"

Blinking is fixed. Tabs jumping is a result of showing number of files and pieces in tab. It's a tradeoff where I think having more info at a glance is more valuable than reducing minor jumping of ui elements. It's not like it jumps when you are trying to use them because switching torrents means your mouse is in the table above. Alternative solution of having min width for tabs looked too weird.

> Maybe some spacing and separators could improve the readability a bit?

I added spacing. It behaves differently from Transgui which has hardcoded widths for each section and just cuts off at the right if window is too narrow. TrguiNG will shrink all elements and I think behaves more gracefully.

You can try the fixes if you compile yourself or wait a few days for next release.

**Comment by qu1ck** [comment]
I looked at qBittorrent api and it is quite different from transmission and would be a lot of work to support. Given that I don't use qBittorrent myself I don't see ever implementing support for it although it's possible in theory. Contributions are welcome.

**Comment by qu1ck** [comment]
Fixed in [v0.3.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v0.3.0).
