### ISSUE TITLE
Clicking empty space doesn’t deselect a torrent

### ISSUE THREAD

**Issue by nicknlsn** [openscopeproject/TrguiNG#70]
This was mentioned by jfeilbach. Would be nice to have the selected torrent(s) be deselected when empty space is clicked.

**Comment by qu1ck** [comment]
I don't see what is the point?

**Comment by jfeilbach** [comment]
Just a minor UI quibble. Clicking empty space in most UX should result in nothing being selected. Feel free to admonish me.

**Comment by qu1ck** [comment]
You obviously don't have enough torrents so that you still have empty space you can click, gotta pump those numbers up :) 

I am not sure if it's true on mac but on linux/win a lot of UI elements have a behavior where once selected you can't go to initial blank state. This probably can be implemented but it's more trouble than it's worth.
