### ISSUE TITLE
Using mapped paths, the route to the basedir of the file is not completed

### ISSUE THREAD

**Issue by elboletaire** [openscopeproject/TrguiNG#80]
I have most of my downloads in a shared directory called media, and I mapped it like so:

    /media=\\elboletaire.loc\media

Now when I try to open a file located in `/media/merged/Downloads/completed/sonarr/` does not throw an error, but instead of opening such folder, it just opens the `media` folder, without completing all the missing part (in this case, `/merged/Downloads/completed/sonarr`)

Is there anything else I should take in mind when configuring it (like, maybe, using regex, which I already tried)? or it may be a bug?

Using version 0.8.1 under windows 11.
![imatge](https://github.com/openscopeproject/TrguiNG/assets/153305/4c8ed85d-26a4-4590-ad25-597e35963d7e)

**Comment by qu1ck** [comment]
Try mounting your share as a network drive so that windows caches the credentials and maintains the connection. Then change the mapping to use the network drive letter instead of URI.

**Comment by elboletaire** [comment]
> Try mounting your share as a network drive so that windows caches the credentials and maintains the connection. Then change the mapping to use the network drive letter instead of URI.

Looks like a bug then if it's not behaving correctly with a domain name, doesn't it?

**Comment by qu1ck** [comment]
Sort of, if it is a bug it's a windows api bug. If I call the [ShellExecuteW](https://learn.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shellexecutew) api and ask it to open `\\a\b\c\d` and it only opens \\a\b` there is not much I can do about it.

But I suspect UNC (network) paths have caveats that are not mentioned in api docs, so I offer the workaround of mounting the network drive. That works reliably for me.

**Comment by qu1ck** [comment]
If there is a better API that I should call instead that I don't know of, I would welcome someone pointing me to it.

**Comment by elboletaire** [comment]
I'm not aware of any windows API, sorry, but the "classic" transmission remote gui (transgui) does not need to mount network drives, maybe you could check there how they're doing it.

If there's no way to solve it, I'd recommend adding a notice in that section of the settings.

**Comment by qu1ck** [comment]
Well transgui uses lazarus function [OpenDocument](https://github.com/transmission-remote-gui/transgui/blob/26a1e99d586c82d01a3816f465976db843992205/main.pas#L7281) which in turn uses the same [ShellExecuteW](https://gitlab.com/freepascal.org/lazarus/lazarus/-/blob/07f7a1931edb0ba6d1dc4db5d7e91ea0c670d464/lcl/include/sysenvapis_win.inc#L345). It's not obvious why their implementation works and mine does not. There is a minor change of passing "open" verb in my version but it should not make a difference, at least in theory. I can't verify it in practice because it works both ways for me.

Here is a build were I modified it to do exactly the same as what transgui does, can you try it?
[TrguiNG_0.8.1_x64-setup.exe.zip](https://github.com/openscopeproject/TrguiNG/files/12615580/TrguiNG_0.8.1_x64-setup.exe.zip)

**Comment by qu1ck** [comment]
By looking at actual api calls with sys api monitor I found that even the difference of "open" verb is not actually there since somehow transgui also passes it even if it's not in lazarus source code (maybe it is built with a very old version?).

But I uncovered another small and seemingly insignificant difference, I don't include trailing slash for folders and don't always swap forward slashes for backslashes in paths. Neither of these _should_ make a difference but I will clean it up anyway.

**Comment by elboletaire** [comment]
> Here is a build were I modified it to do exactly the same as what transgui does, can you try it?

Just tried it. Sadly it still behaves the same way 😞 

> But I uncovered another small and seemingly insignificant difference, I don't include trailing slash for folders and don't always swap forward slashes for backslashes in paths. Neither of these _should_ make a difference but I will clean it up anyway.

Let me know if you want me to try new versions 👍

**Comment by qu1ck** [comment]
Try the [v0.9.0](https://github.com/openscopeproject/TrguiNG/releases/tag/v0.9.0) release. It has the changes discussed above, among other fixes and features.

**Comment by elboletaire** [comment]
Yaaay, it's working noow!! 🎉 

Closing as completed in https://github.com/openscopeproject/TrguiNG/releases/tag/v0.9.0
